#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication -s air    decomposePar -region air
runApplication -s pipe   decomposePar -region pipe

runParallel $(getApplication)

runApplication -s air    reconstructPar -latestTime -region air
runApplication -s pipe   reconstructPar -latestTime -region pipe

#------------------------------------------------------------------------------
