#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

#runApplication blockMesh
restore0Dir

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet
runApplication createPatch -overwrite

touch pipeheaterExchg.foam
buoyantBoussinesqPimpleFoam
#runApplication $(getApplication)
#------------------------------------------------------------------------------
